name: Publish package to GitHub Packages
on:
  release:
    types: [ created ]
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle


          #  - name: Publish artifact
          #    env:
          #       CREDENTIALS: -PGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -PGITHUB_USER=${{ github.actor }}

          #    run: ./gradlew -Pversion=${{github.ref_name}} publish ${CREDENTIALS}
          #  - name: Gradle bygg av services
          #    env:
          #     CREDENTIALS: -PGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -PGITHUB_USER=${{ github.actor }}
          #    run: ./gradlew build ${CREDENTIALS}

      - name: Gradle bygg av services
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: build -PGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -PGITHUB_USER=${{ github.actor }}


      - name: Publish artifact
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: build -Pversion=${{github.ref_name}} publish -PGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -PGITHUB_USER=${{ github.actor }}
